# version of compose
version: "3.8"
# name: maalquran
# list of volumes and named them
volumes:
  # ********** nginx
  # maalquran_nginx_log:
  # ********** nginx
  maalquran_php_sessions:
  # ********** mysql
  maalquran_mysql_lib:
  # ********** redis
  maalquran_redis_data:
  # ********** postgresql
  # postgresql_data:
# list of networks
networks:
  maalquran_qanat:
    driver: bridge
# list of services
services:
# -------------------------------------------------- nginx
  maalquran_nginx:
    container_name: maalquran_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    hostname: ${NGINX_HOSTNAME}
    restart: always
    ports:
      - "80:80"
      - "443:443"
    tty: true
    extra_hosts:
        - "maalquran.local:host-gateway"
    volumes:
      # - maalquran_nginx_log:/var/log/nginx
      - ./src/:/var/www/html/
    environment:
      TZ: ${TIMEZONE}
    networks:
      - maalquran_qanat
    depends_on:
      - maalquran_php
# -------------------------------------------------- php
  maalquran_php:
    container_name: maalquran_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    hostname: ${PHP_HOSTNAME}
    restart: always
    tty: true
    volumes:
      - ./src/:/var/www/html/
      - maalquran_php_sessions:/var/lib/php/sessions
      # - .docker/php/conf/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      TZ: ${TIMEZONE}
      SESSION_HANDLER: redis
      SESSION_PATH: tcp://maalquran_redis:${REDIS_PORT}?auth=${REDIS_PASSWORD}
      SESSION_MAX_TIME_LIFE: 86400
    networks:
      - maalquran_qanat
# -------------------------------------------------- mysql - db
  maalquran_mysql:
    container_name: maalquran_mysql
    image: mysql
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # MYSQL_DATABASE: ${MYSQL_DATABASE}
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TIMEZONE}
    # env_file: mysql.env
    ports:
      - 3316:3316
    volumes:
      # - mysql_data:/var/usr/mysql
      - maalquran_mysql_lib:/var/lib/mysql
      # - ./services/mysql/production/my.cnf:/etc/mysql/my.cnf
    networks:
      - maalquran_qanat
# -------------------------------------------------- phpmyadmin
  maalquran_phpmyadmin:
    container_name: maalquran_phpmyadmin
    image: phpmyadmin
    restart: on-failure
    # entrypoint: ["echo", "Service phpmyadmin disabled"]
    ports:
      - 8194:80
    networks:
      - maalquran_qanat
    depends_on:
      - maalquran_nginx
      - maalquran_php
      - maalquran_mysql
    profiles: ["phpmyadmin"]
    environment:
      PMA_HOST: maalquran_mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1000000000
# -------------------------------------------------- redis
  maalquran_redis:
    container_name: maalquran_redis
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    # command: ["redis-server", "--appendonly", "yes"]
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - maalquran_redis_data:/data
    environment:
      #- REDIS_PASSWORD=${REDIS_PASSWORD}
      # - REDIS_PASSWORD=YOUR_REDIS_PASSWORD
      TZ: ${TIMEZONE}
    profiles: ["redis"]
    networks:
      - maalquran_qanat
#
# eol
